---
title: 放流に意味はあるのか？
author: ''
date: '2022-12-29'
slug: intentional-release
categories:
  - academic
tags:
  - fishery
---

野外で何かしら生物を増やそうとしたとき、もっとも**安直な方法**は「放流」だろう。人が卵から孵化させ、あるところまで育てて外に放す。「元気に暮らしてね」などの言葉とともに、放流イベントとして子供に放流させるケースも多い。

しかし、本当に放流に意味はあるのか？

これまでの研究を見る限り、ほとんどのケースで**放流に意味はない。むしろ、ほぼ確実に弊害がある。**

# 放流の規模

そもそも放流はどの程度の規模で行われているのだろうか？放流にも様々なものがあるが、ここでは「野生集団の増加を目的として、人の手によって（在来の）生物を野外に放す行為」とし、特に天然資源として価値が高い生物を対象としたものに絞る。

天然資源を対象とした放流事業は、想像を絶する数を野外に放している。その顕著な例はやはりサケ類だろう（一般に食卓にならぶサケは「シロサケ」）。[Kitada 2020](https://onlinelibrary.wiley.com/doi/abs/10.1111/raq.12418)にまとめられている統計を見ると、その放流数は1980年代にピークを迎え、日本全国で15 -- 20億尾/年ものシロサケ稚魚が放流されている。地域ごとにみると、西北海道だけで4億尾強/年のシロサケが放流されている。アラスカのPrince William Soundにおけるカラフトマスの放流事業が6億尾強/年なので（[Amoroso et al. 2017](https://cdnsciencepub.com/doi/full/10.1139/cjfas-2016-0334)）、まさに世界最大規模といって相違ない。ほかの日本のサケ類（カラフトマス、サクラマス）をみても、日本全国で1000万尾--1.5億尾が放されており、とんでもない数であることがわかる。もちろん、これらの生産コストはタダではない。シロサケの場合、**1尾あたり2.5円ほどなので、種苗生産そのもののコストだけで年間数40-50億の税金**がつぎ込まれていることになる[^1]。

[^1]: この種苗生産コストに人件費や消耗品などは含まれていないので、実際はもっと膨大な金額になる。

こうした大規模放流は水産資源に限ったものではない。スペインのある地域では、Game birdとして価値の高いRed-legged partridgeという鳥が200万羽/年の規模で放されている（[Negro et al 2001](https://www.sciencedirect.com/science/article/abs/pii/S0006320700001294)）。送粉者として重要なマルハナバチの仲間も、$>10000$ コロニー/年が導入されている地域もある（[Ings et al. 2005](https://link.springer.com/article/10.1007/s00442-005-0081-9)）。

# 放流の効果

これだけ放しているんだから、もちろん増えているんだろう、と多くの人は思うかもしれない。しかし、実際はそうではない。放流効果を検証した研究は必ずしも多いわけではないが[^2]、知見の蓄積している魚類をみると、実は**増えないケースがほとんどである。**それどころか、減る場合も多い。[Araki and Schimit 2010](https://www.sciencedirect.com/science/article/pii/S0044848610004540)では、水産生物の野生集団に対する放流の効果を調べた41の研究をまとめている（メタ解析[^3]）。このうち、野生集団の明瞭な増加をもたらしたケースはたったの3例にとどまっている（[Chan et al. 2003](https://esajournals.onlinelibrary.wiley.com/journal/19395582/), [Berejikian et al. 2009](https://cdnsciencepub.com/doi/abs/10.1139/F09-041?journalCode=cjfas), [Agnalt 2008](https://academic.oup.com/icesjms/article/65/2/164/733653)）。なぜか。

[^2]: もっともこの分野の研究が進んでいるのは間違いなく水産分野であるが、「放す個体をどう育てるか？」（種苗生産）に関する研究は死ぬほどあるのに、「放流で本当に増えたのか？」（放流効果）という疑問に答える研究は本当に少ない。まずこれがひどい。

[^3]: 一あるテーマについて、様々な研究から既存データを統合し、一般的な傾向があるかどうかを探る解析。

1.  **生態系は無限に個体を受け入れられるわけではない。**

    どんな生態系にも「収容力」がある。この収容力を超えた数を放したところで、食べ物の枯渇、生活場の不足などの理由（種内の資源をめぐる競争）から、個体の死亡率は高まる。結果、野外集団の一部を放流個体で「置き換える」だけになってしまい、集団としては増えない（あるいは採算に合わない微増）[^4]。実際に、放流個体による野生個体の置き換えは、魚類で観察されている。国内の事例は[Sahashi et al. 2015](https://onlinelibrary.wiley.com/doi/abs/10.1111/fme.12136)［サクラマス］や[Kitada et al. 2019](https://www.nature.com/articles/s41598-019-39050-3)［マダイ］、海外では[Amoroso et al. 2017](https://cdnsciencepub.com/doi/full/10.1139/cjfas-2016-0334)や[Hilborn and Eggers 2000](https://afspubs.onlinelibrary.wiley.com/doi/abs/10.1577/1548-8659%282000%29129%3C0333%3AAROTHP%3E2.0.CO%3B2)などが詳しい。ただし、ここで「増えない」といっているのは**放流直後の放流＋野生集団の話であり、次世代への繁殖を通じた効果を見ているわけではない。**繁殖を通じた効果の場合は、余計ひどくなる。極端な種内競争が起こるため、繁殖まで生き残る個体が少なくなり、結果として次世代の集団縮小が起こる（[Satake & Araki 2012](https://link.springer.com/article/10.1007/s12080-011-0128-y)）[^5]。これは一般的な数理モデルによる予測だが、その後の研究で、サクラマスでは放流数の増加とともに長期的な集団サイズ（21年の平均密度）が小さくなる傾向が観察されている（[Terui et al. in review](https://www.biorxiv.org/content/10.1101/2022.02.24.481650v1)）。

2.  **寄生虫や病気の蔓延に寄与する。**

    私の知るもっとも有名な例は、カナダのBritish Columbia近海におけるカラフトマスの例である。この例では、カラフトマスにとって極めて厄介な寄生者（sea lice）が養殖池で爆増し、放流個体から野生個体への大規模感染が起こった。その結果、この地域の野生集団のいくつかが絶滅に瀕した（[Krkosek et al. 2007](https://www.science.org/doi/10.1126/science.1148744)）。この研究では、その地域の養殖池に由来する寄生者の蔓延が問題だが、他地域から放流個体を持ち込む場合にも同様のことが起きうる。例えば、アユの冷水病がすぐに思いつく。琵琶湖水系由来のアユは全国に流通、放流されているが、これにともない冷水病が全国に拡散したと考えられている（[Wikipedia](https://ja.wikipedia.org/wiki/%E5%86%B7%E6%B0%B4%E7%97%85)）。ただ、この言説については学術文献に基づく一次情報を見つけられなかったので、あくまで可能性のひとつとしてみておくべきだろう。

3.  **放流個体は野外での生き残りが悪い。**

    魚類以外でもかなり昔から議論されているが、放流個体は野外で生き残りが悪い（[Snyder 1996](https://www.jstor.org/stable/2386850)に初期の議論がよくまとめられている）。これは、人工飼育環境が野外と比べてかなり特殊であることに起因する。例えば、ふんだんに与えられる餌、野外ではありえない高密度などがある。放流個体は、この特殊環境で最後まで生き残った個体である。これらは人工飼育環境ではエリートかもしれないが、野外ではうまく生きられない（サケ類の例：[Sahashi and Morita 2022](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/fee.2457)）。さらに、こうした「不自然な選択」が何世代も繰り返されることで（水産ではよく継代飼育する）、人工環境に適した遺伝子が集団に蓄積する。これらが野外に放されると、野生個体との交配を通じて野生集団に遺伝子が浸透し、その子孫にあたる個体の適応度（生残など）まで低下する（[Araki et al. 2007](https://www.science.org/doi/10.1126/science.1145621)）。なお、この負の効果は、その地由来の魚から卵を採取しても現れる。例えば、[Milot et. al 2012](https://onlinelibrary.wiley.com/doi/full/10.1111/eva.12028)の大西洋サケの例では、放流先の河川に由来する放流個体が、たった一世代の飼育で野外での適応度[^6]が激減したことを示している。なお、先に言及した[Araki and Schimit 2010](https://www.sciencedirect.com/science/article/pii/S0044848610004540)によると、過半数の研究（23/41）で放流個体の適応度低下[^7]が認められている。

[^4]: 私も放流関連の研究には最近関わっているが、数メートルしか幅がないような小さな川に、数万から数十万の稚魚を放しているのを（データとして）見ている。「その川がそんなに受け止められるわけねーだろ！」というのが（河川を研究してきた）私の感覚である。

[^5]: 林業の間引きと逆のことが起こっていると考えるとわかりやすい。

[^6]: ある個体が自身の遺伝子をどれだけ次世代に残せたか、に関する指標。生残率、繁殖効率などが適応度の指標としてよく用いられる。

[^7]: 内訳としては、生残率の低下（捕食に対してより脆弱になるなど）、繁殖効率の低下、（野外での）成長率の低下などが挙げられている。

以上から、「放せば増える」という神話が当てはまるケースは稀といわざるを得ないだろう。[Kitada 2018の総説](https://onlinelibrary.wiley.com/doi/full/10.1111/faf.12271)では、2010年以降の研究も網羅されている。

あと、ここでは当たり前すぎるので省いたが、他地域から個体を持ち込むことは遺伝的攪乱（本来交流のない集団間の交流を促す）を引き起こすので、その観点からも放流はよくない。

# 放流がうまくいくとき

しかし、確かにうまくいっているケースもある。多くの事業で思うような結果が得られない中、なぜ特定の種や状況ではうまくいくのか。これにはいくつかの理由があると考えられる。

成功例１：ホタテ。ホタテは放流事業がもっともうまくいっている事例のひとつだろう（[Kitada 2020](https://onlinelibrary.wiley.com/doi/abs/10.1111/raq.12418)）。私は「ホタテはうまくいくはずがない」と考えていた。というのも、ホタテはろ過食者であるし、半固着性の生物であることを考えると、食べ物や生活場をめぐる種内競争が激しいはずだからである。しかし、先日ホタテの放流事業に詳しい方に話を伺う機会があり、合点した。ホタテの放流事業では、いったん海を「まっさら」にし、ホタテ自身も天敵（ヒトデなど）もいない環境を作ってからホタテ種苗を放すらしい。つまり、不要な競争が起きないよう対象種の個体数がほぼ完全にコントロールされているのだ[^8]。なるほど、そこまで管理すればうまくいく、とは思う。しかし、「海をまっさら」にする環境インパクトは絶大なのではないか、と心配になる。まるで畑ではないか。

[^8]: 「この海域にはこの数まで放してOK」という（環境収容力の）基準があるらしい。

成功例２：危機的な絶滅危惧種。天然資源から話がずれるが、本当に絶滅に瀕した（した）種の再導入はうまくいっているケースが散見される。例えば佐渡のトキ。トキの野生絶滅後、佐渡では2008年に10個体の再導入が行われたようだが、その後順調に個体数を増やしている（[Okahisa et al. 2022](https://onlinelibrary.wiley.com/doi/10.1111/ibi.13071)）。そのほか、アメリカのLittle Colorado RiverではHumpback chubという絶滅危惧種の移植が行われているが、移植先ではうまく集団が増えているようだ（[Yackulic et al. 2021](https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/1365-2664.13908)）。これらのケースに共通しているのは、（１）導入対象種の集団は絶滅した・しそうなほど縮小している。（２）導入個体数が少ない（資源管理のようにとんでもない数を放さない）。（３）種内競争が弱くなりやすい生態的特徴をもつ（寿命が長いなど）。実際、このような条件が満たされる場合に、放流が期待される結果（集団の増加）をもたらすことが理論的に予測されている（[Satake and Araki 2012](https://link.springer.com/article/10.1007/s12080-011-0128-y), [Terui et al. in review](https://www.biorxiv.org/content/10.1101/2022.02.24.481650v1)）。ただし、ここで注意したいのは、保全を目的とした放流であっても、その多くで期待された成果が得られていないという事実である（[Fischer et al. 2000](https://linkinghub.elsevier.com/retrieve/pii/S0006320700000483), [Haag 2012](https://www.amazon.com/North-American-Freshwater-Mussels-Conservation/dp/0521199387)）。この結果をひとつの原因と紐づけることは難しいが、放流先の「場」がそもそも悪いままであること（つまり、環境悪化で生態系の収容力が損なわれている）、そして（先に述べたように）放流個体の野外でのパフォーマンスが良くない、ということとして大体のケースは理解できそうである。

ちなみに、水産学の大御所であるワシントン大学のHilborn博士は、24年前の彼の著作の一つでこう述べている（[Hilborn 1998](https://www.ingentaconnect.com/content/umrsmas/bullmar/1998/00000062/00000002/art00022?crawler=true)）：

> Experience shows that the situations in which stock enhancement is most likely to succeed are (1) those in which sedentary invertebrates can be planted and grown out in **a farm-like operation** and (2) those in which **wild stocks are essentially gone**. (経験上、放流が最も成功しやすい状況は、（1）移動性の低い無脊椎動物を植えて農場のように育てられる場合、（2）野生集団が基本的にいなくなってしまった場合、である。)

# 結論

そもそも、放流のような人為干渉は、本当にそれしか手だてがない場合に「のみ」使われるべき最終手段である。野生集団は、うまく環境を整えさえすれば、余計な手を出さずとも自然と増えるものである。しかし、場が悪くなってしまうと、放しても増えないどころか、様々な悪影響がでる。**一人暮らしの部屋（生態系）に100人押し込むような手段（放流）を改善したところで、増えるわけないことくらい少し考えればわかる**ものだと思ってしまうのだが。まずは部屋を大きくすること（環境改善による収容力の増加）から始めないといけない。Synder博士の約30年前の論文（[Snyder 1996](https://www.jstor.org/stable/2386850)）からの抜粋でしめることにする。

> Captive breeding should be viewed as a ***last resort*** in species recovery and not a prophylactic or long-term solution...（人の手による繁殖は、種の回復における最後の手段と考えるべきであり、予防的あるいは長期的な解決策ではない）
