---
title: いつか誰かが見つけてくれる
author: ''
date: '2022-11-13'
slug: china-japan
categories:
  - academic
  - us life
tags:
  - miscellaneous
---

**「いい研究をしていれば、いつか誰かが見つけて評価してくれる」**

これは正しくもあり、間違いでもある。ひと昔前と異なり、今のアカデミアは電子ジャーナルであふれかえり、無数の論文の波に否応なしに飲みこまれる。その中から真に面白い論文を見つけることは困難で、やはり「ジャーナル」の評判をベースに読むべき論文の優先順位をつけてしまう（この意味においてインパクトファクターは大事である）。こうした中、自分の仕事をより広く知ってもらうためには適切なプロモーションが必要になる。

私はアメリカに来て5年経つが、その中で一番驚いたといっても過言でないのが「グループ内引用」の多さだ。周りをみていると、次のような戦略で自分のニッチを構築し、プロモーションしているように思える。

1.  まず、グループの旗振り役（PI）が大型予算をとり、そのたたき台として意見論文を書く。多くの場合、この段階では必ずしもアイデアを裏打ちするデータがあるわけではなく、既存の知見からうまくロジックを組み立て、意見論文をまとめているように感じる。ちなみに、こうした意見論文はプロポーザルの使いまわしであることが多い。ずるい。

2.  グループ内から意見論文に沿った論文が次々と生まれ、最初の意見論文、先に出た論文をどんどん引用する。なんだか確立されたコンセプトのようになっていく。実のところ、この段階ではグループ内で固めているだけ。

3.  グループ外の人間が面白いと思い、そのコンセプトに沿った論文を書く。ここで初めてそのコンセプトに市民権が付与される。

この文化を見ていると、アメリカで真に新しいアイデアを生み出している人はごくごく一部で、周りがそのアイデアに乗っかる形で潮の流れが出来ている。あくまで私見だが、日本の生態学会のほうがユニークなアイデアを見ることが多い。にも関わらず、それが大きな潮の流れを作ることはとても少ない。なぜなら、日本の研究文化はステップ１の部分が圧倒的に弱く、ステップ３で他のグループのアイデアに加担（というと言葉が悪いが）しているケースがほとんどだからだ。また、日本をフィールドとしたより関連した論文よりも、欧米の有名論文を引用しているのをよく見かける。

一方、この流れに大きなくさびを入れつつある国がある。「中国」だ。中国が科学の各分野で世界を席巻しつつあるのは周知の事実だが、これはただの数の力や偶然ではないと思う。確かな戦略がある。

2018年のアメリカ生態学会（ESA；Ecological Society of America）に参加したときのこと。ESAはいわゆるマンモス学会で、年会の参加者数は3000人を上回る。規模が大きく、研究対象も多岐にわたるので、会期中にはグループごとにMixer（懇親会）があるのが通常だ。私はAsianグループに興味があり参加してみたのだが、この時の光景がすさまじいものだった。50-70人の参加者がいるなかで、日本人は私を含めて二人、韓国人が一人、その他はすべて中国人であった。また、その多くはアメリカで学位を取得しようとしている人、Faculty positionを得てアメリカに拠点を築いている人、中国からアメリカで活躍している中国人を「ヘッドハンティング」しようとスカウトに来ている人であった。簡単に自己紹介する中で、スカウト目的で中国から参加している人が、「我々中国はアメリカで活躍する君たちをいつでも好待遇で受け入れる準備ができている！」とも言っていた。つまり、アメリカに人材を送り込むだけでなく、欧米につながりをもった研究者を積極的に引き込むことで、自国の活性化につなげようとしているだろう（直接聞いたわけではないので定かではないが、ほぼ間違いない）。また、研究の仕方も「チーム戦」がうまい。彼らの研究を見ていると、とにかく自国のいい研究を積極的に引用する姿勢がすごい[^1]。最初は欧米の真似事だったかもしれないが、そこには自身の立派な哲学ができており、今では中国の戦略として確立したものになっているように感じる。

[^1]: これを真似て、私はできるだけ日本のいい研究を引用するようにしています。

昨今、生態学の主要ジャーナルでは中国発の論文を見ない日はなくなったが、これは数の力だけで説明がつくものではない。確固たる戦略が実を結んだ結果とみたほうがいいだろう。似たようなことが他の分野でも起きているのだろうか？

日本の話に戻る。私が日本の国としての戦略にあれこれ口を出すつもりもないし、どうすればいいのかも皆目見当つかない。中国と同じことをしようとしたところで、現在の日本の大学や研究機関にそんな体力（財源）は残されていないと感じる。それを十二分に分かったうえで、ただひとつ苦言を呈するとすれば、**「いい研究をしていれば、いつか誰かが見つけてくれる」が成り立つのはマジョリティーに属している場合のみ**、という事実をあまりに多くの人が認知していないことだ。欧米、そして中国が研究のマジョリティーとなりつつある中で、極東の研究者の「いい研究」が知れ渡る機会は想像以上に限られている。個人でできることとすれば、とにかく海外大学も含めてセミナーで飛び回り、積極的に自分の仕事を売ることだろう。それが日本の研究者コミュニティにとってどれほど意味があるのかわからないが、国として学術がすさんだ状況を見る限り、（若手は）個人としてあがく以外に方法はない。

日本の平均的な研究力・創造力はアメリカと比べてそん色がないどころか、大きく上回っているとすら感じる。しかし現状では、多くの欧米人はそんなことは知る由もなく定年まで過ごすのだろう。それをなんとももどかしく感じる。
