---
title: 海外で研究職を探す：ファカルティ応募編
author: ''
date: '2019-09-02'
slug: jobhunt
categories:
  - academic
tags:
  - job hunt
---

## Summary

海外学振が2年目に差し掛かったところで、そろそろ次の職を探さないとまずいと思い、ファカルティポジションに応募することにした。**いつプータローになるかわからないという恐怖におびえながら**、海外のファカルティポジションに応募した自分の経験をまとめてみたい。

## 選考の流れ

海外学振の研究員としてアメリカで1年暮らしたころ、ファカルティへの応募を考え始めた。しかし、アメリカでファカルティポジションに就いている自分の姿をイメージすることが全くできなかった。というのも、言語に関する自信がないこともあったのだが、それ以上に大学の教育システム、文化に対する理解もとても十分とは思えなかったからだ。しかしながら、日本のアカデミアの状況が良くなるようにも思えなかったので、自信はないもののとりあえず出してみようと決意した。

アメリカの場合、（１）書類審査、（２）Online Interview、（３）Campus Interviewの3段階の選考がなされることが多い。100通（普通の大学）から300通程度（トップの大学）の応募書類のなかからOnline面接に呼ぶ候補者を決め（10-15人程度）、さらにOnline面接を通じてCampus面接によぶ3-4人の候補者を選ぶ。いずれも全く知らないものばかりであり、書類審査を通ったとしてもその後の面接を潜り抜けられる気は全くしなかった。蓋を開けたら何とかなっていたのだが。

## 書類審査

アメリカのファカルティポジションに応募する際には、大体次の書類が求められる。

- Cover letter
- CV
- Research Statement
- Teaching Statement
- Diversity Statement
- Reference

**はて何を書けばいいやら**という感じである。Diversity Statementに至っては頭から湯気が出る。幸い、友人や先輩らがサンプルとなる書類をシェアしてくれたので、これらに何を書けばいいのか大体検討をつけることができた。また、[THE PROFESSOR IS IN](https://www.amazon.com/gp/product/0553419420?ie=UTF8&tag=randohouseinc8340-20&linkCode=as2&camp=1789&creative=9325&creativeASIN=0553419420 "The professor is in")という本には非常に役立つ情報が満載である。書き始める前に一通り読むと時間を節約できる。

### Cover Letter

この書類は選考委員会が一番最初に目を通す書類なので、自分がいかにそのポジションにフィットしているかを端的に記す必要がある。簡単な自己紹介から始め、自分のスキルや経験がいかにポジションにマッチしているのかを書く。もし予算獲得歴や教育歴があるのならば、そういった側面も積極的に売り込んでいくのがいいのだろう（私はほとんどなかったので特に書かず）。Cover Letterがひどいと、おそらく他の書類をきちんと見てもらえない（アメリカ、Ecologyの分野では、1つのポジションに対して最低でも80-100倍の応募があるので）。最初の1-2パラグラフでガツンとアピールできる書類を準備したい。

### Research Statement

1-2ページの長さで、仮に着任できたらどんな研究プロジェクトを展開するのか書く。比較的書きやすい部分ではあるのだが、（Research Universityであれば）一番がっつりみられる部分でもあるので、気合を入れて書きたい。特に大事なのは、大学の施設、これまでの自分の経験、今のFacultyメンバーなどを顧みながら、**現実的かつ魅力的なプラン**を書くことなのだと思う。どんなに他の書類が優れていても、ここで非現実的なプランが書かれていたら（非常に特殊な研究施設が必要など）それだけで落とされてしまうだろう（と誰かが言っていた）。一方、大学側が特定の研究施設の利用を期待しているような募集のかけ方をする場合もある。その場合、そうした施設でしかできない研究プログラム（そしてそれを支える経験）を提案できればかなり強い、たぶん。また、アメリカのファカルティポジションは研究室を運営できる人間を探しているので、その点も意識しながら（つまり、学生をどう巻き込んでいくのか）書く必要もあるのだろう。

### Teaching Statement

日本で教育を受けてきた人は、Teaching Statementを書くのにえらく苦労するはずである。というのも、通常、アメリカではPh.D在籍時にTAとして授業の一部を担当するのが一般的であり、この経験をもとにしながらTeachingに対する基本的な考え方やアプローチをつらつらと書くのが普通だからだ。私の場合、全くといっていいほどTeachingの経験はなかったが、ポスドクの時にInformalなジャーナルクラブなどを主宰していた経緯に触れながら、どう授業を展開するかを書いた。やはりここでも、自分の経験に基づいて書くことが大事らしい。素晴らしく見えるTeaching Planを書いたとしても、経験に基づかないものは「机上の空想」として捉えられるということなのだろう。この書類を書く段階になり、Teachingの経験をまったく積んでこなかったことを後悔した。

### Diversity Statement

これは最近の潮流のようで、この書類が要求される場合が多くなっているようだ（まだないところも多い）。この書類では、Minority（Native Americanなど）である人たちにとって公平な研究環境をどう作っていくのか、というのが見られるようだ。個人的に、これはInternationalな人間が強みを出しやすいところだと思う。というのも、例えばアメリカに来た日本人は、「日本で超大多数派（日本人）に属した経験」、そして「アメリカで外国人という少数派に属した経験」の双方を持つので、この点で他の候補者から差別化を図れる。

### Reference

誰がReferenceになっているのかもかなり影響がある気がする。これは来るとよくわかるが、アメリカはよくも悪くも「コネ社会」なので、選考委員の人がReferenceと知り合いだったりすると、Interviewに呼ばれる可能性は（3%くらい）上がるかもしれない。なので、「呼ぶか、呼ばないか」の瀬戸際にあった時、どちらに転ぶかを左右する要因には十分なり得る。いろんな人と、いい関係をつくっておこう、がんばろう。

## Online Interview

書類審査を通過すると、突然電話がなり、「あなたはインタビューに呼ばれました。いつが都合がいいですか」みたいに聞かれる。候補日の中から日時を指定し、ビデオコールで選考委員とInterviewすることになる。私は15通くらい応募し、一つの大学からOnline Interviewに呼ばれた。そのほかはあえなく撃沈したようだが、こういうのは応募したら忘れるくらいがちょうどいいのだと思う（9割方書類で落ちるので）。

Online Interviewで初めて選考委員と顔を合わせることになる。私の時は選考委員は5名で、このうちの1名は大学院生だった。これはアメリカでは一般的なようで、新しく来るファカルティに対し、学生の目線からも評価する意図があるようだ。

Online Interviewを開始すると、各委員から矢継ぎ早に質問が繰り出される。"What's your research program at our department?"や"What makes you a valuable addition to our department?"などなど。Interviewの時間は限られているので、最初から長々と答えず、肝の部分を端的に答える。そののちに、細かい質問を相手にさせるゆとりを与えることが大事なようだ。短すぎてもダメなので、そのバランスが難しいのだけど。

ちなみに、私はOnline Interview中にネットワークトラブルがあり、非常に聞き取りづらいなかでの面接となった（質問を何度も聞き返すこともあった）。質問の中で"What is the greatest challenge so far?"というものがあったのだが、それは「**まさに今です**」と答えたい気持ちだった。

## Campus Interview

大失敗に終わったと思われたOnline Interviewだったが、なぜかCampus Interviewに呼ばれることになった（通信エラーにより、英語力の低さがバレなかった可能性）。ここまでくると候補者も絞られてくるので、一人につき「**2泊3日**」という膨大な時間を費やしてInterviewが行われる（ちなみに、交通費や宿泊費はすべて大学が持つ）。

初日の夕方に現地につくと、選考委員会の一人が空港まで迎えに来てくれる（油断ならないのは、**すでにここから面接は始まっている**という事実である）。そして2日目も朝ごはんからInterviewであり、プレッシャーのため飯がまったくのどを通らない。ご飯のあとに大学に行くと、30分刻みでDepartmentのファカルティ一人ひとりとInterviewをするスケジュールが組まれている。お昼は大学院生とグループInterview。午後にもInterviewをし、最後の締めにInterviewのメインイベント「Job Talk」が行われる。Job Talkは40-45分程度の発表なのだが、この出来が可否を大きく左右する。Job Talkののち、またDepartmentの人と晩御飯を食べに行き、ここでもまたJudgeされるのである（ひぃぃ）。3日目も昼過ぎまで30分刻みのInterviewをし、夕方にやっと岐路につく、というものだった。
　Interviewが終わった後は本当に憔悴する。が、Interviewのコツとしては、事前にファカルティの研究テーマを把握していき、30分間会話が途切れないよう（楽しく会話できるよう）努めることのようだ。鬼のような質問攻めにあうことを想定していたのだが、実際のところは、楽しく会話をしながら「こちらが必要とする情報（研究環境、生活環境）」を引き出す場として活用できるのだ。答えることの準備以上に、こちらから**どの人にどんな話題を持っていくべきか**の準備のほうが大事だと感じた（こっちが80%くらいを占めていた）。なお、Ecological Society of Americaにおいて、「答えられるようにしておくべき質問集」「尋ねるべき質問集」なるものがまとめられている（[Link](https://esajournals.onlinelibrary.wiley.com/doi/epdf/10.1890/0012-9623(2006)87[155:IFAJ]2.0.CO%3B2)）。これはとても役に立った。

## 終えてみて

Campus Interviewののち、1週間たたないころにオファーの連絡をいただく。初めての経験だらけだったのだが、思い返すと意図せず準備できていた部分があったとも思う。それは、それまでにアメリカの大学でセミナーシリーズのスピーカーとして呼ばれたことが何度かあり、その中で30分ずつ個別に人と会うことをやってきたからである。あの経験はCampus Interviewの予行演習としてうまく機能していた気がする。あと、まだまだ改善の余地はあるのだが、日本にいるときから地道に言語の訓練は積んでいたことが、（思いがけずに）研究職を得ることにつながった。蛇足するが、日本のポジションにも応募はしていたもののすべて落ちていたので、これがなければ今頃プータローとしてその辺をはいつくばっていたかもしれない（ただ、まだ安心はできないので、今後はテニュア獲得に向けて頑張らなければ）。