---
title: 恥ずかしい英語の間違い
author: ''
date: '2019-06-03'
output:
  blogdown::html_page:
    toc: true
slug: bad-english
categories:
  - us life
tags:
  - english
---

## Summary
アメリカに来て二年が経ったが、いまだに恥ずかしい英語の間違いを繰り返してばかり。そんな失敗談のまとめ。

## No thanks
だれも知り合いがいない国際学会に一人で参加し、Burger Kingに行った時の話。当時（博士課程2年）、英語がおぼつかないながらも何とかハンバーガーを注文し、席で普通に食べていた。そうすると、店員の人がテーブルを回りながらお客に声をかけている。

**"How XXXing?"**

断片的にしか聞き取れていないのでなんのやり取りなのかさっぱりわからない。そしてついに私のテーブルにも来て、何やら同じようなことをしゃべりだす。何を言っているかわからない。だけど何か返さなければならない。そんな中、私は必死になにか手掛かりとなる情報を探し、その店員さんがケチャップとマスタードを持っていることに気が付き、**これは「ケチャップいる？」とかその辺を聞いているに違いない！**と合点した。味はしっかり濃い目だったので、調味料の類はいらないと思い、自身満々でこう答えた。

**"No thanks"**

周りの人たちが「ぎょっ」とし、店内の空気が凍ったのを覚えている。店員はバツの悪い笑顔を浮かべて去り、なにかこちらを睨みつけながら他の店員と話している。いったい、なにが起こったのだ。

あとあと思い返すと、おそらくあれは

**"How is everything?"**

と話しており、「ハンバーガーどう？」みたいに聞いていたのだと思う。それに対して私は、「**全然ないわ**」みたいな返しをしたことになる。ああ。

## What are you working on?
ポスドクの飲み会があり、それに参加して話していた時の話。目の前でビールを飲むブラジル人のポスドクがいたので、なんの研究をしているのか聞いてみようと思い、**"What are you working on?"**と聞いた。そうすると、

**"I'm working on beer."**

と返ってきた。確かにそうだ。**彼はビールを飲んでいる。**無意味に現在進行形にしてはならないことを学んだ。

## Everything
同じ部屋にいるポスドクにペンを借りようと思い、声をかけた時の話。貸して、というと（パンパンのペン立てを見せながら）どのペンがいいと言ってきたので、どれでもいいよ（Anything）、というつもりで

**"Everything"**

と答えてしまった。今でも恥ずかしい。

## XXXgraXXX
アメリカに住んで1年半がたち、次のポジション探しをしていた時の話。海外学振の任期は2年間なので、そろそろ次の当てを見つけなければならない。そう思い、アメリカと日本のポジションに応募していた。アメリカのポジションはすべてOnline Applicationなので楽なのだが、日本のポジションは海外からでも郵送で応募しなければならない。その時、応募書類のデータをCDに入れて送ってください、とするポジションがあり、（それだったらメールで出させてくれよ、とか思いながら）USPSの事務所に郵送手続きに向かった。

受付の姉ちゃんに封筒の中身は何だと聞かれCDだと答えると、「～でないこと」を証明する項目に署名してくれといわれるが、～の部分が**XXXgrXXX contents**としか聞こえず、「え？え？」と聞き返しまくった。そうすると、姉ちゃんの機嫌はどんどん悪くなってゆく。そこで目を落として書類を見ると

**Pornographic**

と、書いてある。あぁ、そうか。エッチなDVDを国外輸送されると困るから、そうではないことを証明してくれといっていたのか。どうやら私は、***USPSの受付の姉ちゃんにPornographicを連呼させる***という離れ業をやってのけたらしい。ごめんなさい。

## Can I borrow a restroom?
友人の家に招かれ鍋をしていた時の話。トイレに行きたくなったので「トイレ貸して」のつもりで

**"Can I borrow a restroom?"**

というと、友人は軽く笑いながら"**No**"といった。え、マジ、と困惑していると、理由を教えてくれた。Borrowはペンなどのように「持ち手から”取って”借りる」場合を指すらしく、今回の場合のように使うと「***トイレ丸ごと持ち出して借りてもいい？***」という意味になるらしい。みなさん、Useを使いましょう。
