---
title: 論文を書くときの留意点
author: ''
date: '2021-12-07'
slug: checkpoint
output:
  blogdown::html_page:
    toc: true
categories:
  - academic
tags:
  - writing
---

論文のドラフトをあげたら、以下の点を確認する。

## Structure

### Introduction

-   パラグラフ間の論理的つながりが明確

-   大きな枠組みの中で新奇性を述べている

-   対象とするシステムの「必然性」が明確

-   データの質と整合性が取れている

-   仮説が単純かつ明快

### Methods

-   情報を出す順番が適切

-   パラグラフごとに情報が整理されている

-   理論・統計は専門外の人にも伝わるように書かれている

-   パラメータ名の重複や説明漏れがない

-   パッケージやソフトウェアのVersion情報に誤りがない

### Results

-   Methodsを詳しく読まずとも結果が理解できる

-   結果の意味するところが述べられている

-   不確実性の記述が適切

-   効果量の記述が明確

### Discussion

-   仮説・問いに対する答えが明確であり、答えの意義を広い枠組みのなかで捉えている（最初のパラグラフ）

-   各結果の解釈が端的に述べられている

-   複数の解釈がある場合、それらが網羅されている

-   弱みや限界に言及がある

-   今後の大きな展開がイメージできる（最後のパラグラフ）

### Additional point

-   読み落とされたくない重要情報は表現を変えて複数個所に配置する（MethodsとDiscussionなど）

-   弱みより強みが前面に出る巧妙な論理展開がなされている（特にDiscussionの弱みや限界に言及する際）

## Paragraph

-   トピックセンテンスからパラグラフの内容が類推できる

-   一貫してひとつの内容について述べている

-   最後の文は結論を述べている

-   文同士の論理的つながりが明確（however, similarly, also, thereforeなどが文頭になくとも論理がつながる）

-   クラウズ（which, that）は多くとも二つまで

-   同じ表現・動詞の繰り返しがない

## Sentence

-   重文（XXX and YYY）は重文にすることで理解が促される場合にのみ用いられている

-   主語と動詞のつながりが明確な文構造を用いている（"**Many bird species distributed in this island** eats large fruits" (読みにくい) \< "**This island** harbors many bird species that eat large fruits" (読みやすい))

-   一文が短い

-   because, as, sinceなどの表現を効果的に用いている
