---
title: 「放流しても魚は増えない」について
author: ''
date: '2023-03-11'
slug: release-exotic
categories:
  - academic
tags:
  - fishery
  - non-native species
---

先日、放流に関する論文（\"[Intentional release of native species undermines ecological stability](https://www.pnas.org/doi/10.1073/pnas.2218044120)\"）を発表したところ、メディアに広く注目いただき、とてもうれしく、そして驚いてもいます。「放せば増える」という図式はとても直感的なため、それに反する結果がでたことに驚きを感じたのだろうと推察しています。一方、SNSなどで反応を見ていると、いくつか説明を補足したほうがいいだろうと思ったものがありました。これだけ反響があったことですし、誤解や拡大解釈があってもいけないので、2点取り上げようと思います。

## 外来種は増えている

「放流しても魚は増えない」に対する反応（あるいは反証）として最も大事だと感じたのは、「外来種は放流で増えている」というものでした。これはもっともな疑問かと思います。この点に関する私の見解は以下の通りです。

**（１）外来種の放流は、水産重要種などの意図的な放流とは様式が全く異なる。**外来種の放流は（意図されない）突発的なイベントであり、（公に）大規模かつ継続して行われることはまずないでしょう（ペットを逃がすなど[^1]）。放すといっても多くて数百尾でしょう。このため、放流に伴う「過度の競争」は起きにくいと考えられます。もし、バスやギルを小さな池に毎年何万尾も放流すれば、「過度の競争」は起き、サクラマスに見られた「放流で減る」ようなことは起きると思います。もちろん、バスやギルが減る前に在来種がまず食い尽くされるわけですが。。。

[^1]: いまだにいいことと思ってやってる人もいるとは思いますが...絶対にやめましょう。

**（２）「外来種にとって」の器はからっぽ。**もう一点異なるのは、受け手となる生態系にその種がいないことです（最初の導入であれば）。これは、外来種にとってみればガラガラのレストランに入るようなものです。例えば、在来種がワイワイと暮らす池に10匹のオオクチバスを放したとしましょう。在来種というご馳走がたんまりある上に、競争相手となる他のオオクチバスはたったの9匹しかいません。この状況で「過度の競争」が起きるわけがありません[^2]。外来種の繁栄は、今回の結論の反証であるかのように見えますが、実は同じ現象を別の角度からみているに過ぎません（器が空いていれば、適度に放すと増える）。なので、むしろ論文の結論を支持しているといってもいいでしょう。地域絶滅した種の再導入を例に、同様の議論は過去の[ポスト](https://ecological-stats.netlify.app/2022/12/29/intentional-release/)でも書いています。

[^2]: 日本には、オオクチバスと同じ「ニッチ（食べ物や住処などによって定められる種の特徴）」を占める種が少ないことも関係していると思います。

忘れてならないのは、大半の外来種は「侵略的（増えすぎて問題になる）」ではない、という事実です。オオクチバスやブルーギル、アメリカザリガニのように増えて問題なっている外来種をみると、持ち込めば必ず増えると誤認しそうになります。しかし、実際のところ、ほとんどの外来種は定着できずに死に絶えることがわかっています[^3]。これには持ち込まれた先の環境（非生物・生物含む）がその種に適していなかったためと考えられ、外来種研究の分野では何十年も前から言われている常識です。つまり、**場が整わない限り生き物は増えない、という事実は何十年も前から突き付けられている**のです。

[^3]: だからといって持ち込んでいい、というロジックにはなりません。

## 放流≒ダメなこと？

これは繊細な内容になりますが、今回の論文は**すべての放流を否定するものではありません。**放流が必要になるケースは確かにあります。地域絶滅した種を再導入したい場合はその一例でしょう。ほかにも、集団から遺伝的多様性が失われ、奇形が多くでてしまうような場合にも放流は必須でしょう。しかし、だからといって**放流は環境破壊の免罪符にはならない**、というのが一番大事な点になると思います。論文中の最後のパラグラフでは以下のように述べました：

> While socioeconomic analysis is required to provide detailed guidance on release programs, it is clear that habitat conservation should be prioritized for the sustainability of natural resources. Protected areas and environmental restoration are promising tools to conserve biodiversity, and a smart spatial design is integral to achieving successful conservation. For example, coordinated placement of conservation sites considering spatial biodiversity patterns is crucial in improving the ecological outcomes (53--56). Governance may also play a central role in enforcing environmental legislation, potentially determining the effectiveness of conservation investment (57). These considerable potentials indicate that viable management options exist before blindly accepting intentional release. Without a comprehensive framework that appreciates the ecological integrity of natural communities, the intentional release will never be effective but impairs biodiversity.
>
> 放流のあり方を導くためには社会経済的視点からの分析が必須であるが、今回の結果から、自然資源の持続可能性のためには生息地の保全を優先すべきであることは明らかである。保護区や環境修復は生物多様性を保全するための有望な手段であり、それらの適切な空間配置によってその効果は大きく改善される。例えば、生物多様性の広域分布を考慮した適切な保護区の配置は、保全目標を果たす上で極めて重要である(53-56)。また、ガバナンスは、環境法の施行において中心的な役割を果たし、保全投資の効果を左右する可能性がある（57）。これらの大きな可能性は、意図的な放流を盲目的に受け入れる前に、実行可能な保全手法が存在することを示している。生態系がどのように維持されているのかを深く理解し、その理解に基づく管理方策を立てない限り、放流は決して効果的ではなく、むしろ生物多様性の喪失を加速させることになる。

放流は「XXX尾放しました！」という実績が得やすい、というのはよくわかります。漁協の方は特に、増殖義務を果たさなければならないという板挟みの状況にあるのもわかっています。それゆえ、この放流問題は、**現行の管理システムの問題（管理権限者）**だと思います。また、これだけ放流を推進しておきながら、その効果の厳密な評価をほとんど行ってこなかった点にも大きな疑問が残ります。私にとってこれは深いミステリーです。

状況を見極めさえすれば、放流は一手段として十分機能しうると思います。しかし、**放流を主軸に保全や資源管理を行うには無理があるでしょう**。放流の怖いところは、放した直後は増えるので、あたかも傷が癒えたか（環境がもどった）のように見えるところです。しかし、実際は傷は癒えてなどおらず、モルヒネで痛みをごまかしているのではないでしょうか。

放流のかじ取り役である水産庁のみなさんが、今回の結果をどう受けとるのか、怖くもあり、楽しみでもあります。痛みと向き合う方針転換があることを切に願います。
