---
title: 海外で働くということ
author: ''
date: '2023-09-08'
slug: outside
categories:
  - us life
  - academic
tags:
  - miscellaneous
  - english
---

気が付いたら、アメリカで働き始めて6年以上経つ。
ときに「もう英語はすっかりペラペラなんですか？」と聞かれる。
もしかしたら、そうなのかもしれない。
だが、英語に対する劣等感が消えたことはないし、これから消えることもないと思う。

もともと海外志向が強いわけでもなく、受験以上の英語を積極的に勉強したわけでもない。
しかし、博士一年のときに初めて参加した国際学会のインパクトがすごかった。
日本のコミュニティーの閉鎖性を否応なしに突き付けられ、「受け身」のまま日本に居座ってはいけないと思い立った。
このとき25歳。
予算を確保し、アメリカに渡航したのは30歳のとき。
30歳を過ぎてから、言葉も文化も異なる国に順応するのはそれなりに辛い。

私の場合、日本から予算（海外学振）をいただいてアメリカにポスドクとして来た。
そして、2年のポスドク期間の後、幸いにも現在の職場でファカルティ―ポジション（教員）のオファーをいただけた。

当然、教員として「雇用」されたからには相応の能力が要求される。

自分の研究室の学生やポスドクの給料を支えられるだけ研究費を勝ち取らなければならない。
指導する学生とうまくコミュニケーションできなければならない。
授業をゼロから作り、平然とこなさなければならない。
これらを、Native相手に英語でやらなければいけない。
アメリカの教員としての常識を把握するには、2年というポスドク期間はあまりにも短い。

教員として働き始めた最初の一年は、数えきれないほどの「わからない」を、一つ一つ潰していく年だった。
研究費を申請する際の手続き・書類の量が段違いに多い。
そもそもどこからお金を引っ張ってくればいいのかわからない。
職員会議（教授会）に出ても、聞いたことのない英語略称が飛び回るので置いてけぼりをくらう。
そんな状況でも、論文の生産性を落としてはならない。

だが、教員としての3年目が始まる頃、仕事の感触がこれまでと異なるのを感じる。
英語でも相手の「人となり」がわかるようになる。
議論をリードすることがそれほど苦痛ではなくなる。
一つ不安が消えては新たな不安が出てくるが、とりあえず一つずつ克服することにした。

今、複数PIからなる研究プロジェクトをリードとしてプロポーザルを書いている。
20代半ばのころは、英語で予算交渉のような繊細なやりとりする羽目になるとは想像だにしなかった。
何とかなっているので、いろいろ何とかなるようだ。
